# Actuator endpoint
management:
  endpoint:
    health:
      show-details: always

# Spring profile
spring:
  profiles:
    active: dev

server: 
      port: 9254

# Info endpoint
info:
  app:
    version: @project.version@
